// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR2zmPcn-QnjA1zHND4CTTgyHhaQPSrWQ',
    appId: '1:4692632334:web:6904014bb0821383426d5f',
    messagingSenderId: '4692632334',
    projectId: 'ditonton-c9c0a',
    authDomain: 'ditonton-c9c0a.firebaseapp.com',
    storageBucket: 'ditonton-c9c0a.appspot.com',
    measurementId: 'G-N1NFD1RQX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWMgIuA5SA-Dkx9d3d1U2eDwwKyapCtoI',
    appId: '1:4692632334:android:976dfd1e96ed0b67426d5f',
    messagingSenderId: '4692632334',
    projectId: 'ditonton-c9c0a',
    storageBucket: 'ditonton-c9c0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_bBlbvx1uC6BANCfg9961q4s9WiTk_84',
    appId: '1:4692632334:ios:89935582f07a5d8f426d5f',
    messagingSenderId: '4692632334',
    projectId: 'ditonton-c9c0a',
    storageBucket: 'ditonton-c9c0a.appspot.com',
    iosClientId: '4692632334-0om1e3thb2netd85j88bghhhumr4llfk.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
